config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
	get 'about', to: 'pages#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
               uniqueness: { case_sensitive: false }, 
               length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
               uniqueness: { case_sensitive: false }, 
               format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	#xcdsfsf
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be in to perform that action"
            redirect_to root_path
        end
    end

    #moi branch3
    #newbranch4
    #branch4
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end
	def new
		@article = Article.new
	end
	
	def edit
	end

	def update 
		if @article.update(article_params)
			flash[:success] = "Update succesfully"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Create succesfully"
			redirect_to articles_path
		else
			render "new"
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Articles was deleted"
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end
		def article_params
			params.require(:article).permit(:title, :description)
		end
		def require_same_user
		  if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
		  end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end

	def about
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email.downcase])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You are successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was somthing wrong with your login information"
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
        redirect_to user_path(@user)
        else
        render 'new'
        end
    end
    def edit
    end
    def update
        if @user.update(user_params)
        flash[:success] = "Your account was updated succesfully"
        redirect_to articles_path
        else
        render 'edit'
        end
    end
    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles by user have been deleted"
        redirect_to users_path
    end
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end
    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size:  80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
    def javascript_exists?(controller_name)
        File.exist?(Rails.root.join("app", "frontend", "packs", "#{controller_name}.js"))
    end
    
    def stylesheet_exists?(controller_name)
        File.exist?(Rails.root.join("app", "assets", "stylesheets", "#{controller_name}.scss"))
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="card">
		<div class="card-header">
			<%= link_to article.title, article_path(article), class: "article-title" %>
		</div>
		<div class="card-body">
			  <p class="card-text"><%= truncate(article.description, length: 100) %></p>
			  <div class="article-meta-details">
				<small>Create by: <%= article.user.username if article.user %>,
					<%= time_ago_in_words(article.created_at) %> ago, 
					last update: <%= time_ago_in_words(article.updated_at) %> ago</small>
			  </div>
	  		<% if logged_in? && (current_user == article.user || current_user.admin?) %>
          	<div class="article-actions">
            	<%= link_to "Edit article", edit_article_path(article), class:"btn btn-xs btn-primary" %>
            	<%= link_to "Delete this article", article_path(article), method: :delete,data:{confirm: "Are you sure you want to delete the article?"},
                        class:"btn btn-xs btn-danger"%>
          	</div>
        	<% end %>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<div class='row' >
	<div class='col-12'>
	  <%= form_for(@article, :html => {class: "form-horizontal center", role: "form"}) do |f| %>
		<div class="form-group row">
		  <div class="control-label col-sm-2" align="right">
			<%= f.label :title %>
		  </div>
		  <div class="col-sm-8" align="center">
			<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
		  </div>
		</div>
		<div class="form-group row">
		  <div class="control-label col-sm-2" align="right">
			<%= f.label :description %>
		  </div>
		  <div class="col-sm-8" align="center">
			<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
		  </div>
		</div>
		<div class="form-group row">
		  <div class="col-sm offset-2">
			<%= f.submit class: 'btn btn-primary btn-lg' %>
		  </div>
		</div>
	  <% end %>
	  <div align="center">
		[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
	  </div>
	</div>
  </div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container" >
    <h1 align="center">Listing all articles</h1>
    <%= render 'article', obj: @articles %>
      <div class="pagination">
        <%= will_paginate %>
      </div>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="card">
	<% if @article.user %>
		<ul class="listing">
			<div class="form-group row" align="center">
		  	<div class="card-body bg-light col-md-4 offset-4">
				<li>Created by:</li>
				<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
				<li class="article-title">
			 	<%= link_to @article.user.username, user_path(@article.user) %>
				</li>
				<li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
		  	</div>
			</div>
		</ul>
	<% end %>
	<div class="card-header">
		<h4 class="article-title" align="center">Description:</h4>
	</div>
	<div class="card-body">
		<p class="card-text"><%= simple_format(@article.description) %></p>
		<div class="article-actions">
			<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  			<%= link_to "Edit article", edit_article_path(@article), class:"btn btn-xs btn-primary" %>
 	 		<%= link_to "Delete this article", article_path(@article), method: :delete,data:{confirm: "Are you sure you want to delete the article?"},
															class:"btn btn-xs btn-danger"%>
			<% end %>
  			<%= link_to "View all articles", articles_path, class:"btn btn-xs btn-success" %>
		  </div>
  	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
<footer class="footer">
    <small>
      Link facebook: <a href="https://www.facebook.com/profile.php?id=100012082206799">Nguyễn Văn Công</a></br>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<br><div class="container">
</br>
<div class="row">
  <div class="col-sm">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%>' align="center" >
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a><%= link_to "Articles", articles_path , class: "nav-link"%></a>
      </li>
      <li class="nav-item">
        <a><%= link_to "Users", users_path, class: "nav-link" %></a>
      </li>
      <%if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class ="dropdown-item" href="<%= new_article_path %>">New Article</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <% end %>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%if logged_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a><%= link_to "Edit your profile ", edit_user_path(current_user), class: "dropdown-item" %></a>
            <div class="dropdown-divider"></div>
            <a><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link"%>
      </li>
      </ul>
      <% else %>
        <%= link_to "Log in", login_path, class: "nav-link"%>
        <%= link_to "Sign up", signup_path,  class: "nav-link"%>
        <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag controller_name if stylesheet_exists?(controller_name) %>
    <%= javascript_pack_tag controller_name if javascript_exists?(controller_name) %>
  
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This my blog</h1>

<%= link_to 'home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Hello</h1>
	<%= link_to "sign up now", signup_path, class: "btn btn-primary btn-lg"%>
</div>

<%= link_to "Blog", articles_path %> || <%= link_to 'about', about_path %> <br>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>

    <div class="form-group row">
      <div class="col-md-8">
        <div class="col-sm offset-3">
          <div class="card card-danger" >
            <div class="card-header" >
              <h2 class="card-title", align="center">
                <%= pluralize(obj.errors.count, "error") %>
                prohibited this article being saved:
              </h2>
              <div class="card-body">
                <ul>
                  <% obj.errors.full_messages.each do |msg| %>

                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
<div class='row' >
	<div class='col-12'>
	  <%= form_for(@user, :html => {class: "form-horizontal center", role: "form"}) do |f| %>
		<div class="form-group row">
		  <div class="control-label col-sm-2" align="right">
			<%= f.label :username %>
		  </div>
		  <div class="col-sm-8" align="center">
			<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
		  </div>
		</div>
		<div class="form-group row">
		  <div class="control-label col-sm-2" align="right">
			<%= f.label :email %>
		  </div>
		  <div class="col-sm-8" align="center">
			<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
		  </div>
    </div>
    <div class="form-group row">
		  <div class="control-label col-sm-2" align="right">
			<%= f.label :password %>
		  </div>
		  <div class="col-sm-8" align="center">
			<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
		  </div>
		</div>
		<div class="form-group row">
		  <div class="col-sm offset-2">
			<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
		  </div>
		</div>
	  <% end %>
	  <div align="center">
		[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
	  </div>
	</div>
  </div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">
  All Alpha Bloggers
</h1>
<div class="pagination">
  <%= will_paginate %>
</div>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="form-group row">
        <div class="card-body bg-light col-md-4 offset-4", align="center">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
             <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <% if logged_in? and current_user.admin? %>
          <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles"} %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
<div class="pagination">
  <%= will_paginate %>
</div>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class = "row">
  <div class="col-md-4 offset-md-4 " align="center">
    <%= gravatar_for @user, size: 130%>
  </div>
</div>
<div class="container"  >
  <h4 align="center"><%= @user.username%>'s articles</h4>
  <%= render 'articles/article', obj: @user.articles %>
  <div class="center">
    <%= will_paginate @user_articles %>
  </div>
</div>